kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-shanying-uniapp
  namespace: dev-test
  labels:
    app: test-shanying-uniapp
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/alias-name: Uniapp Test Service
    kubesphere.io/maxSurgePod: '2'
    kubesphere.io/minAvailablePod: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-shanying-uniapp
  template:
    metadata:
      labels:
        app: test-shanying-uniapp
      annotations:
        kubesphere.io/containerSecrets: '{"uniapp":"harbor-id"}'
    spec:
      containers:
        - name: uniapp
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:v1.0.0.$BUILD_NUMBER
          ports:
            - name: http-80
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: harbor-id
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
